### ISSUE TITLE
"Something went wrong. Please try again." on my profile 

### ISSUE THREAD

**Issue by ad-m** [tipsy/profile-summary-for-github#102]
After a longer processing period, I receives for my user account ```ad-m``` the message:

> Something went wrong. Please try again.

In HTTP requests I have see request to ```https://profile-summary-for-github.com/api/user/ad-m``` with result ```503 Service Unavailable```.

**Comment by ad-m** [comment]
I starred this repository long time ago.

**Comment by tipsy** [comment]
Your profile works, but took longer than 30 seconds to build: https://profile-summary-for-github.com/user/ad-m

Heroku times out the request at 30 second. We could switch to a submit+poll based system, but I don't have much time for this project at the moment.

**Comment by ad-m** [comment]
I see now response. Thanks for you tool!
