### ISSUE TITLE
Sometimes profiles are not loading

### ISSUE THREAD

**Issue by theapache64** [tipsy/profile-summary-for-github#104]
![image](https://user-images.githubusercontent.com/9678279/82653387-c1b42180-9c3c-11ea-87de-2d90551eb75c.png)

**Comment by theapache64** [comment]
and now it's not loading.

![image](https://user-images.githubusercontent.com/9678279/82654519-7ef34900-9c3e-11ea-9dfa-1ec451a83026.png)


Is the server down mate ?

**Comment by tipsy** [comment]
Heroku times out the request if it doesn't finish in 30 seconds, and Linus has a really big profile. It seems to work though? https://www.profile-summary-for-github.com/user/torvalds

**Comment by theapache64** [comment]
Awesome. now it loads.

but I am getting a different error for another user.

![image](https://user-images.githubusercontent.com/9678279/82655992-9f240780-9c40-11ea-91a7-9d084ec775d3.png)

**Comment by tipsy** [comment]
Yeah, that's not an error, it's a mechanism so people/bots can't drain all the requests. Just star the repo and refresh. You can unstar it after.

**Comment by theapache64** [comment]
I've tried restarring the project. but it didn't work. I am still getting the same error.

**Comment by tipsy** [comment]
Oh, I see that we made it stricter. I get this error message: 

```
The app is running with two GitHub tokens, giving 10 000 requests per hour. 
The first 5000 requests can be used to build any profile, 
while the last 5000 requests are reserved for users building their own profile. 
To confirm that you're building your own profile, we check if you've starred the repository.
```

**Comment by tipsy** [comment]
This only shows on the search page, not if you try to directly open a profile.

**Comment by tipsy** [comment]
If you're really curious about Jake's profile you can clone the repo and launch the project with your own GitHub token (or you can wait until the ratelimit resets).

**Comment by theapache64** [comment]
Alright. I actually use this tool very much. It's clean and really usable.

I've been building a chrome extension to add more features to GitHub (for my personal purpose). One of them is redirecting to this tool from a GitHub profile page with a single click.

![image](https://user-images.githubusercontent.com/9678279/82662534-aa306500-9c4b-11ea-82e4-13f8c72ddfec.png)

![image](https://user-images.githubusercontent.com/9678279/82662585-c03e2580-9c4b-11ea-9e18-f6dab29d4688.png)

**Comment by tipsy** [comment]
Ah, that's cool! I'm not working on this project at the moment, but I'd be happy to review pull requests if you want to make some changes.

**Comment by theapache64** [comment]
Sure.
