### ISSUE TITLE
Feature : Navigate to repo

### ISSUE THREAD

**Issue by theapache64** [tipsy/profile-summary-for-github#105]
Would it be good If clicking on the repo name opens the repo in a new tab?

![image](https://user-images.githubusercontent.com/9678279/82737390-77bb6080-9d4e-11ea-99b5-3506bc0f9113.png)

@tipsy

**Comment by tipsy** [comment]
Sure! Clicking on the chart itself already does that, but if you want to override the default behavior of clicking on the repo-name then that's fine.

**Comment by theapache64** [comment]
Ohh I see. I didn't know that. Then it's not necessary
