### ISSUE TITLE
Top 5 languages title is not centered

### ISSUE THREAD

**Issue by Dysproz** [tipsy/profile-summary-for-github#108]
Thank you for this project :)

However, I've added it today to my profile and I noticed that title of Top 5 languages pane is not centered and is overlaps right frame.

Here's the pane:
![](https://raw.githubusercontent.com/Dysproz/Dysproz/master/profile-summary-card-output/default/1-repos-per-language.svg)

**Comment by tipsy** [comment]
Feel free to submit a PR :)

**Comment by Dysproz** [comment]
If only I knew this this language ;)

**Comment by Dysproz** [comment]
Solved

**Comment by tipsy** [comment]
🤔
