### ISSUE TITLE
Unnecessary Legend Labels

### ISSUE THREAD

**Issue by Attacktive** [tipsy/profile-summary-for-github#114]
I got one GitHub star in total. 🤣
But in [my profile summary](https://profile-summary-for-github.com/user/Attacktive), the *Star per Language* section has extra legend labels:
![image](https://user-images.githubusercontent.com/66462458/173490089-e616410a-afc0-4f45-9221-4041976414d1.png)

These can be removed I think and I'm going to do it myself.

**Comment by tipsy** [comment]
This is live on the website now :)
