### ISSUE TITLE
Data Doesn't seem to be accurate in Nature (Please check below quarterly graph and then my profile)

### ISSUE THREAD

**Issue by ChintzRuparel** [tipsy/profile-summary-for-github#120]
<img width="420" alt="Screenshot 2022-10-07 at 23 25 21" src="https://user-images.githubusercontent.com/51440734/194620084-dd6e5348-61ed-48cc-bf25-e30d331eae52.png">

**Comment by iProdigy** [comment]
The last data point represents 2022-Q4. Q4 started on October 1st, so 49 commits in one week appears is reported by this visualization. That said, while this may clear up some confusion, github claims you have had 61 commits in October, so there is still some discrepancy (may be attributable to timezones, but will investigate)

**Comment by ChintzRuparel** [comment]
Hey @iProdigy, 

Woah! The explanation and the point was as clear as possible. This waved off all the confusion I had. 
The both repositories showing less number of commits than actual was because of Jupyter Notebook pushes are counted as one. Hence sparking this confusion. 

Thanks a lot! 
Do drop me if you wanna collaborate on some project!

Regards and Thanks, 
@ChintzRuparel

**Comment by ChintzRuparel** [comment]
Hey @iProdigy, 

The QUERY has been resolved. 
This issue stands as closed. 

Regards and Thanks, 
@ChintzRuparel
