### ISSUE TITLE
Too many repos

### ISSUE THREAD

**Issue by standardgalactic** [tipsy/profile-summary-for-github#130]
It looks like I cannot use the tool. I have 18,032 repos, which is probably causing the issue.

**Comment by tipsy** [comment]
Yeah, that's too many repos 😁

**Comment by standardgalactic** [comment]
I plan to start removing some of the uninteresting or outdated ones once I reach 150,000 because I think any more than that might be unmanageable. So maybe the tool will be fixed by then.
