### ISSUE TITLE
rename the project

### ISSUE THREAD

**Issue by tipsy** [tipsy/profile-summary-for-github#77]
GitHub has taken note of the project and kindly asked me to change the name. Instead of having a name like `github-something`, they prefer if people use `something-for-github`. `profile-summary-for-github` is a pretty obvious candidate for a new name, but maybe there are better alternatives.

**Comment by josejnra** [comment]
What about `profile scraping for github` or `profile outline for github`?

**Comment by tipsy** [comment]
@josejnra I just went with the obvious one.
