### ISSUE TITLE
Keep get `Couldn't build profile for <github-username>`

### ISSUE THREAD

**Issue by stamaimer** [tipsy/profile-summary-for-github#82]
I keep get `Couldn't build profile for <github-username>` on live and local deployment.

**Comment by iProdigy** [comment]
I believe the problem lies in how the application determines whether a user has starred the project.

As in #83, running the app in unrestricted mode (don't need to star) [yields the profile correctly](https://i.imgur.com/rvSeFhq.png).

**Comment by iProdigy** [comment]
@stamaimer your issue is actually that you do not have the repo starred.

**Comment by stamaimer** [comment]
After star the repo, I can get the profile summary on live. But still can't get result on local deployment.

**Comment by iProdigy** [comment]
are you sure you are not running out of remaining api requests? The default is 50/hr unless you supply an api token (5000/hr). With larger profiles it's possible to consume all 50.
