### ISSUE TITLE
Star-check is slow

### ISSUE THREAD

**Issue by tipsy** [tipsy/profile-summary-for-github#87]
Usually this isn't a problem, (since traffic is low these days), but it takes a long time to check if a user has starred the repo (seems to be about 1s per 100 stars the user has given). Should perhaps look at optimizing this. Any thoughts @iProdigy?

**Comment by iProdigy** [comment]
That PR will help a little but yeah we are currently requesting starred repos 100 at a time until we find our repo or there are no more pages left... worth investigating more optimal api usage

**Comment by tipsy** [comment]
Without looking at the code, I think it should be possible to ask how many stars a user has, then fetch the pages in parallel manually.

Another option is to build and maintain a set of users who have starred the repo, and merge the 100 latest entries into this set upon every request 🤔 

Both options sound a bit boring to implement, and this isn't really required unless the app starts trending again.

**Comment by tipsy** [comment]
@iProdigy I made a fix (or a hack) in 3886d8e5933f7f2deba0804b2f993bcada61b734.

The code works like this:
* On init, read all stars into memory
* On call to `hasStarredRepo`, merge the last page of stars into memory, then `find` user.

I can think of some cases where this will fail, but not very realistic ones. Let me know if you think I overlooked something.

**Comment by iProdigy** [comment]
Should have some time in the upcoming days to review this
