### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by maxemann96** [tipsy/profile-summary-for-github#95]
Using this nice tool for my useraccount results in displaying no data
https://profile-summary-for-github.com/user/maxemann96

I think that it can crash because a public repository from me is currently in a broken status (github is working on it). But I don't know if this is the issue
![grafik](https://user-images.githubusercontent.com/4399206/47946647-c4420f80-df0e-11e8-801e-e3aa8f493c5c.png)

Edit:
Other Accounts are working well

**Comment by iProdigy** [comment]
The application is working as [intended](https://github.com/tipsy/profile-summary-for-github/blob/master/src/main/kotlin/app/UserCtrl.kt#L24); you just don't have any public, non-empty repositories that aren't forks.

**Comment by maxemann96** [comment]
Oh, dont know this, sorry for stealing your time
