### ISSUE TITLE
Private repo support?

### ISSUE THREAD

**Issue by wangsijie** [tipsy/profile-summary-for-github#96]

**Comment by ProgrammingSam** [comment]
It would be very appreciable 😄

**Comment by caseykey** [comment]
Any news on this? Maybe we can include local repositories if it's easier than private repo access?

**Comment by tipsy** [comment]
It's not really hard, it just requires github oauth integration. If you want to implement it, I'd be happy to review.

**Comment by caseykey** [comment]
> It's not really hard, it just requires github oauth integration. If you want to implement it, I'd be happy to review.

I would like to contribute but I am a novice with Kotlin, and I am not familiar with the project structure. What files would you recommend I focus on?

**Comment by Markkop** [comment]
This would be pretty cool. Does anyone have a fork with this? I can try to learn some Kotlin to make it happen

**Comment by wangsijie** [comment]
2y passed, does any one solved this? If not, I would like to make a PR but need to learn Kotlin first.

**Comment by tipsy** [comment]
No one has worked on it, as far as I know!

**Comment by ajmeese7** [comment]
> 2y passed, does any one solved this? If not, I would like to make a PR but need to learn Kotlin first.

@wangsijie be sure to link back to this thread if you do, that way I'll get an update!
